name: Build with CMake

on: [push, pull_request]

env:
  # CMake build type (Debug, Release, RelWithDebInfo or MinSizeRel)
  BUILD_TYPE: Release

jobs:
  windows:
    name: Windows (build and test)
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install dependencies
        run: .\packaging\build-dependencies-msvc.bat
        
      - name: Configure
        run: cmake -B build -DBUILD_TESTS=OFF -DUSE_TENSORFLOW=ON -DCMAKE_PREFIX_PATH=%CD%\packaging\msvc

      - name: Build
        run: |
          set PATH=%PATH%;%CD%\packaging\msvc\bin
          cmake --build build --config ${{env.BUILD_TYPE}} --parallel

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: essentia-build
          path: build/
